<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- A generic arm segment macro -->
  <xacro:macro name="arm_segment" params="prefix parent length radius color *origin">
    <joint name="${prefix}_joint" type="revolute">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${prefix}_link"/>
      <axis xyz="0 0 1"/>
      <limit lower="-3.14" upper="3.14" effort="100" velocity="1"/>
    </joint>

    <link name="${prefix}_link">
      <visual>
        <origin xyz="${length/2} 0 0" rpy="0 ${PI/2} 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${length}"/>
        </geometry>
        <material name="${color}"/>
      </visual>
    </link>
  </xacro:macro>
</robot>