import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Define __dirname for ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const PROJECT_ROOT = path.resolve(__dirname, '..');
const OUTPUT = path.join(PROJECT_ROOT, 'public', 'sample_point_cloud.ply');

// Overridable count so large files can be generated for performance testing,
// e.g. PLY_COUNT=1000000 npm run generate:ply
const COUNT = Number(process.env.PLY_COUNT) || 20000;
const RADIUS = 1.0;
const GOLDEN_ANGLE = Math.PI * (3 - Math.sqrt(5));

// Fibonacci sphere sampling with RGB vertex colors and a subtle radial wobble so the
// sample reads as a cloud rather than a perfect sphere.
const rows = [];
for (let i = 0; i < COUNT; i++) {
  const y = 1 - (i / (COUNT - 1)) * 2; // -1..1
  const r = Math.sqrt(Math.max(0, 1 - y * y));
  const theta = GOLDEN_ANGLE * i;
  const x = Math.cos(theta) * r;
  const z = Math.sin(theta) * r;
  const wobble = 1 + 0.03 * Math.sin(i * 2.7) * Math.cos(i * 0.9);
  const red = Math.round(((x + 1) / 2) * 255);
  const green = Math.round(((y + 1) / 2) * 255);
  const blue = Math.round(((z + 1) / 2) * 255);
  rows.push(
    `${(x * RADIUS * wobble).toFixed(6)} ${(y * RADIUS * wobble).toFixed(6)} ` +
      `${(z * RADIUS * wobble).toFixed(6)} ${red} ${green} ${blue}`,
  );
}

const header = [
  'ply',
  'format ascii 1.0',
  'comment Generated by scripts/generate_sample_point_cloud.js',
  `element vertex ${COUNT}`,
  'property float x',
  'property float y',
  'property float z',
  'property uchar red',
  'property uchar green',
  'property uchar blue',
  'end_header',
].join('\n');

fs.writeFileSync(OUTPUT, `${header}\n${rows.join('\n')}\n`);
console.log(`Wrote ${COUNT} points to ${OUTPUT}`);
